services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/tmp/db
volumes:
  mongodb_data:
    driver: local