spring:
  application:
    name: spring-mvc
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            view: INFO